# Generated by Django 5.1 on 2024-08-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Headline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=500)),
                ("published_at", models.DateTimeField()),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
