# Generated by Django 5.1 on 2024-08-31 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("price", models.IntegerField(blank=True)),
                ("image", models.FileField(upload_to="static/assets/img")),
                ("description", models.TextField()),
                ("phone", models.CharField(max_length=15)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_item",
                        to="user.customuser",
                    ),
                ),
            ],
        ),
    ]
