# Generated by Django 5.1 on 2024-08-31 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("product_quantity", models.IntegerField()),
                ("product_description", models.TextField(blank=True, null=True)),
                (
                    "product_image",
                    models.ImageField(null=True, upload_to="static/assets/img"),
                ),
                ("product_grade", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="user.customuser",
                    ),
                ),
            ],
        ),
    ]
