# Generated by Django 5.1 on 2024-08-31 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Iot_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=10)),
                ("humidity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("moisture", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("nitrogen", models.DecimalField(decimal_places=2, max_digits=10)),
                ("phosphorus", models.DecimalField(decimal_places=2, max_digits=10)),
                ("potassium", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iot_data",
                        to="user.customuser",
                    ),
                ),
            ],
        ),
    ]
