# Generated by Django 5.1 on 2024-08-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="iot_data",
            name="ph",
            field=models.DecimalField(decimal_places=2, default=7.0, max_digits=10),
            preserve_default=False,
        ),
    ]
